Set FontSize 24
Set Width 1200
Set Height 600
Type "terminal-palette"
Sleep 1.5s
Enter
Sleep 1.5s
Type " "
Sleep 250ms
Type " "
Sleep 250ms
Type " "
Sleep 250ms
Type "l"
Sleep 1.5s
Type "k"
Sleep 1.5s
Escape
Type "[Cl"
Escape
Type "[C       sx"
Escape
Type "[B"
Enter
Type " "
Sleep 250ms
Type " "
Sleep 250ms
Type " "
Sleep 250ms
Escape
Type "[C"
Sleep 1.5s
Type "l"
Escape
Type "[D"
Sleep 1.5s
Type "a"
Escape
Type "[C     "
Sleep 5s
